/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  resourceSidebar: [{type: 'autogenerated', dirName: '.'}],
  policiesSidebar: [
    {
      type: 'category',
      label: 'Legal',
      items: [
        'policies/terms-of-use',
        'policies/privacy-policy',
        'policies/service-terms',
        'policies/data-processing-addendum',
        'policies/service-credit-terms',
      ],
    },
    {
      type: 'category',
      label: 'Policies',
      items: [
          'policies/usage-policies',
          'policies/sharing-publication-policy',
          'policies/coordinated-vulnerability-disclosure-policy',
      ],
    },
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
